# Generated by Django 5.0.3 on 2026-02-21 13:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
